### ISSUE TITLE
Tabbed content container

### ISSUE THREAD

**Issue by mbifulco** [gymnasium/gym-ui#22]
As seen in various places on [the home page](https://thegymnasium.com):

![image](https://user-images.githubusercontent.com/1844496/64696543-a4537480-d46c-11e9-84af-2e19b1d45a58.png)

![image](https://user-images.githubusercontent.com/1844496/64696606-d1a02280-d46c-11e9-8249-fcc2ecea8954.png)

![image](https://user-images.githubusercontent.com/1844496/64696652-f1cfe180-d46c-11e9-9108-862a54257e7d.png)

This view contains: 
- [x] a container with a background and text color set by its parent
- [x] a centered tab with a quadrilateral polygon shape that overlaps the previous content area
- [x] title text that has a top and bottom margin set (so it appears below the tab and above any content below
- [x] a main content area

**Comment by alihamoody** [comment]
The tabs are designed to alternate colors when stacked. This is the default behavior if no background or text color is provided.
