### ISSUE TITLE
Color Definitions

### ISSUE THREAD

**Issue by mbifulco** [gymnasium/gym-ui#6]
We should create something like an enum or a specific exported class/object in the codebase to represent the colors commonly used on gymnasium.

This should include:
- [x] black and various shades of gray
- [x] white
- [x] orange
- specific colors for each course type:
  - [x] red 
![image](https://user-images.githubusercontent.com/1844496/64694543-dca48400-d467-11e9-9576-3a92f227ea66.png)

  - [x] purple 
![image](https://user-images.githubusercontent.com/1844496/64694553-e1693800-d467-11e9-850a-c360e2e03305.png)

  - [x] green 
![image](https://user-images.githubusercontent.com/1844496/64694560-e4fcbf00-d467-11e9-803c-3a89b48f66a6.png)

  - [x] teal 
![image](https://user-images.githubusercontent.com/1844496/64694563-e9c17300-d467-11e9-8f30-1d84536ebbb1.png)

**Comment by alihamoody** [comment]
Done.
`src/styles/index.ts`
